server:
  port: 31450
spring:
  application:
    name: xc-service-manage-media-processor
  data:
    mongodb:
      uri: mongodb://root:1@192.168.163.130:27017
      database: xc_media
#rabbitmq配置
  rabbitmq:
    host: 192.168.163.128
    port: 5672
    username: guest
    password: guest
    virtual-host: /
xc-service-manage-media:
  mq:
    queue-media-video-processor: queue_media_video_processor
    routingkey-media-video: routingkey_media_video
  upload-location: D:/Devsoft/JAVAInstall/ffmpeg/video/upload/
  video-location: D:/Devsoft/JAVAInstall/ffmpeg/video/lesson/
  ffmpeg-path: D:/Devsoft/JAVAInstall/ffmpeg/ffmpeg-20180227-fa0c9d6-win64-static/bin/ffmpeg.exe